### ISSUE TITLE
Define react-jsonschema-form extension mechanism

### ISSUE THREAD

**Issue by mavarazy** [RxNT/react-jsonschema-form-conditionals#10]

**Comment by zboldyga** [comment]
I know Sandeep has mentioned this to us, but I think we should not consider it as a requirement while building this module. We don't know much about exactly what their use cases are. 

If it's OK with you, let's close this issue and if RxNT wants to look at it later down the line they can find your idea here.

**Comment by mavarazy** [comment]
Draft seems to good enough for now
