### ISSUE TITLE
conditions documentation?

### ISSUE THREAD

**Issue by zboldyga** [RxNT/react-jsonschema-form-conditionals#42]
This is a note for a few weeks from now... We can come back to this during the knowledge transfer sprint.

In each object specified in the rules array, it looks like we need to specify a conditions property and an event property. There are examples in our documentation of how to use the event property, but it seems like we're deferring to documentation for other projects for how to use conditions.

I think for the sake of the main client (RxNT), we might want to make it simpler for them to quickly understand how to use the tool. Maybe we give documentation for a default engine choice (whichever engine RxNT is using)?

I'm thinking that if it's not dead simple, they aren't going to continue to use the tool. I don't think Thomas & Sandeep have time to look thru code; they'll probably want the READMEs to be fully comprehensive.

**Comment by mavarazy** [comment]
@zboldyga Can you specify what kind of use cases, do you want to see?
Conditionals are separated in 2 parts.
- rules-engine, which is used by default and also by RxNT
- conditionals - action mechanism, which is more generic
I've tried to do my best to describe all the basic scenarios, but I can try to add something that would be more user friendly, If you think this is not enough.
