### ISSUE TITLE
Fails to run rules if initial form data is undefined

### ISSUE THREAD

**Issue by Steffan-Ennis** [RxNT/react-jsonschema-form-conditionals#46]
https://github.com/RxNT/react-jsonschema-form-conditionals/blob/61b08b8c4de59789259192b97115d047b12bed88/src/applyRules.js#L51

Could pass in an empty object when initial form data is undefined

**Comment by deepan-itela** [comment]
I have the same issue.

**Comment by mavarazy** [comment]
@Steffan-Ennis @deepan-itela Are you on the latest version?

https://github.com/RxNT/react-jsonschema-form-conditionals/blob/61b08b8c4de59789259192b97115d047b12bed88/src/rulesRunner.js#L44-L46

There is a check in rulesRunner, that ignores undefined and null formData.
I'll add this anyway, just curious, how to reproduce this

**Comment by deepan-itela** [comment]
I am using version 0.0.3

**Comment by manojItela** [comment]
I tried version 0.3.9 also.

**Comment by mavarazy** [comment]
@deepan-itela Can you switch to the latest version of conditional project, to verify this is still happening?
