### ISSUE TITLE
Remove "hidden" elements of schema from form data

### ISSUE THREAD

**Issue by donalmurtagh** [RxNT/react-jsonschema-form-conditionals#49]
Given this schema
```
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "nameHider": {
      "type": "boolean"
    }
  },
  "required": ["name", "nameHider"]
} 
```
And the following rule which hides the `name` field if `nameHider` is true
```
  const rules = [{
    conditions: {
      nameHider: {is: true}
    },
    event: {
      type: "remove",
      params: {
        field: "name"
      }
    }
  }];
```
If the following actions are performed

1. Set the `name` field to "Bob"
2. Set the `nameHider` field to true

I would expect the form data to be: 
```
{"nameHider": true}
```
But instead it is:
```
{"nameHider": true, "name": "Bob"}
```
I guess I could implement this as a custom action, but IMO this ought to be performed by the `remove` action.

**Comment by mavarazy** [comment]
@donalmurtagh `remove` only changes the `schema` and `uiSchema`, it does not change `formData`, so that in case condition change again user would not have to input something he already specified before.

Custom action is the right way to go here.

**Comment by donalmurtagh** [comment]
@mavarazy as you said, a benefit of using the `remove` action is that values entered in conditional fields are _remembered_. However, if hidden field values are retained in `formData`, they will be included in the submitted data. In my experience, in almost all cases, you do not want the values of hidden conditional fields to be included in the submitted data.

Of course, I could implement a custom `removeSchemaAndData` action, that removes hidden conditional fields from the schema and `formData` but then I lose the aforementioned benefit of the `remove` action.

Something like the following would achieve the "best of both worlds"

1. When the form is being completed, use the `remove` action to hide conditional fields, but retain their values in `formData`
2. When the form is submitted, evaluate all `remove` conditions against the submitted `formData`. 3. Any conditions in (2) that are true/truthy, should have the corresponding fields removed from `formData`

**Comment by donalmurtagh** [comment]
I implemented this as a custom action

```
import remove from "react-jsonschema-form-conditionals/lib/actions/remove"
import ObjectUtils from "../ObjectUtils"
import {validateFields} from "react-jsonschema-form-conditionals/lib/actions/validateAction"
import PropTypes from "prop-types"

/**
 * This adds a custom "removeAll" action to react-jsonschema-form-conditionals.
 * The difference between "remove" and "removeAll" is that the former removes hidden conditional fields from the schema,
 * whereas the latter also deletes their values them from the model.
 */
function removeAll (params, schema, uiSchema, formData) {
  remove(...arguments);
  ObjectUtils.deletePropertyPath(formData, params.field);
}

removeAll.propTypes = {
  field: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.arrayOf(PropTypes.string),
  ]).isRequired,
};

removeAll.validate = validateFields("removeAll", function ({field}) {
  return field;
});

export default {
  removeAll: removeAll
}
```
